# Generated by Django 6.0.3 on 2026-04-05 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveSmallIntegerField()),
                ('round_number', models.PositiveSmallIntegerField()),
                ('race_name', models.CharField(max_length=255)),
                ('circuit_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('race_date', models.DateField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('processing', 'Processing'), ('failed', 'Failed')], default='upcoming', max_length=20)),
                ('fastf1_event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('populated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['season', 'status'], name='idx_race_season_status'), models.Index(fields=['race_date'], name='idx_race_date')],
                'constraints': [models.UniqueConstraint(fields=('season', 'round_number'), name='uniq_race_season_round'), models.CheckConstraint(condition=models.Q(('season__gte', 1950)), name='race_season_gte_1950'), models.CheckConstraint(condition=models.Q(('round_number__gte', 1)), name='race_round_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='DriverMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveSmallIntegerField()),
                ('driver_code', models.CharField(max_length=3)),
                ('consistency_score', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('raw_stddev_seconds', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('normalized_stddev_seconds', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('normalized_cv', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('valid_lap_count', models.PositiveSmallIntegerField(default=0)),
                ('excluded_lap_count', models.PositiveSmallIntegerField(default=0)),
                ('excluded_by_reason', models.JSONField(blank=True, default=dict)),
                ('avg_pace_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('avg_qualifying_position', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_race_position', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('race_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('qualifying_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('value_index', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pace_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('consistency_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('insufficient_data', models.BooleanField(default=False)),
                ('season_aggregate', models.BooleanField(default=False)),
                ('formula_version', models.CharField(default='consistency_v1', max_length=40)),
                ('computed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_metrics', to='api.race')),
            ],
            options={
                'indexes': [models.Index(fields=['race', 'consistency_score'], name='idx_metric_race_consistency'), models.Index(fields=['season', 'value_index'], name='idx_metric_season_value'), models.Index(fields=['driver_code', 'season'], name='idx_metric_driver_season')],
                'constraints': [models.CheckConstraint(condition=models.Q(('season__gte', 1950)), name='metric_season_gte_1950'), models.UniqueConstraint(condition=models.Q(('season_aggregate', False)), fields=('race', 'driver_code'), name='uniq_metric_race_driver_non_agg'), models.UniqueConstraint(condition=models.Q(('season_aggregate', True)), fields=('season', 'driver_code'), name='uniq_metric_season_driver_agg')],
            },
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_code', models.CharField(max_length=3)),
                ('driver_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('driver_name', models.CharField(max_length=120)),
                ('constructor_name', models.CharField(max_length=120)),
                ('grid_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('finish_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('status_text', models.CharField(blank=True, max_length=120, null=True)),
                ('fastest_lap', models.BooleanField(default=False)),
                ('laps_completed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.race')),
            ],
            options={
                'indexes': [models.Index(fields=['race', 'finish_position'], name='idx_result_race_finish'), models.Index(fields=['race', 'constructor_name'], name='idx_result_race_constructor'), models.Index(fields=['driver_code'], name='idx_result_driver_code')],
                'constraints': [models.UniqueConstraint(fields=('race', 'driver_code'), name='uniq_result_race_driver'), models.CheckConstraint(condition=models.Q(('points__gte', 0)), name='result_points_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='StintData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_code', models.CharField(max_length=3)),
                ('driver_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stint_number', models.PositiveSmallIntegerField()),
                ('compound', models.CharField(blank=True, max_length=20, null=True)),
                ('lap_start', models.PositiveSmallIntegerField()),
                ('lap_end', models.PositiveSmallIntegerField()),
                ('laps_in_stint', models.PositiveSmallIntegerField()),
                ('avg_lap_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('median_lap_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('min_lap_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('max_lap_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('degradation_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('pit_in_lap', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pit_out_lap', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('computed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stints', to='api.race')),
            ],
            options={
                'indexes': [models.Index(fields=['race', 'driver_code'], name='idx_stint_race_driver'), models.Index(fields=['race', 'compound'], name='idx_stint_race_compound'), models.Index(fields=['race', 'lap_start'], name='idx_stint_race_lap_start')],
                'constraints': [models.UniqueConstraint(fields=('race', 'driver_code', 'stint_number'), name='uniq_stint_race_driver_stint'), models.CheckConstraint(condition=models.Q(('lap_start__gte', 1)), name='stint_lap_start_gte_1'), models.CheckConstraint(condition=models.Q(('lap_end__gte', 1)), name='stint_lap_end_gte_1'), models.CheckConstraint(condition=models.Q(('laps_in_stint__gte', 1)), name='stint_laps_count_gte_1')],
            },
        ),
    ]
