# Generated by Django 6.0.3 on 2026-04-05 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_code', models.CharField(max_length=3)),
                ('driver_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('laps_count', models.PositiveSmallIntegerField(default=0)),
                ('best_sector1_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('best_sector2_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('best_sector3_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('median_sector1_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('median_sector2_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('median_sector3_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('best_lap_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('theoretical_best_lap_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('delta_to_theoretical_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('computed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_aggregates', to='api.race')),
            ],
            options={
                'indexes': [models.Index(fields=['race', 'theoretical_best_lap_seconds'], name='idx_sector_race_theoretical'), models.Index(fields=['driver_code'], name='idx_sector_driver_code')],
                'constraints': [models.UniqueConstraint(fields=('race', 'driver_code'), name='uniq_sector_race_driver')],
            },
        ),
    ]
