# Generated by Django 6.0.3 on 2026-05-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_drop_django_builtin_auth_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverSeasonSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_code', models.CharField(max_length=3)),
                ('year', models.PositiveSmallIntegerField()),
                ('constructor', models.CharField(blank=True, max_length=120, null=True)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('wins', models.PositiveSmallIntegerField(default=0)),
                ('podiums', models.PositiveSmallIntegerField(default=0)),
                ('poles', models.PositiveSmallIntegerField(default=0)),
                ('fastest_laps', models.PositiveSmallIntegerField(default=0)),
                ('races_entered', models.PositiveSmallIntegerField(default=0)),
                ('dnfs', models.PositiveSmallIntegerField(default=0)),
                ('computed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['driver_code'], name='idx_season_summary_driver'), models.Index(fields=['driver_code', 'year'], name='idx_season_summary_driver_year'), models.Index(fields=['year', 'position'], name='idx_season_yr_position')],
                'constraints': [models.UniqueConstraint(fields=('driver_code', 'year'), name='uniq_driver_season'), models.CheckConstraint(condition=models.Q(('year__gte', 1950)), name='season_summary_year_gte_1950')],
            },
        ),
    ]
