# Generated by Django 6.0.3 on 2026-05-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_race_event_format_race_session1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceresult',
            name='time',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
