# Generated by Django 6.0.3 on 2026-05-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_raceresult_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceresult',
            name='time',
        ),
        migrations.CreateModel(
            name='ConstructorStandings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'constructor_standings',
                'indexes': [models.Index(fields=['year'], name='idx_constructor_standings_year')],
                'constraints': [models.CheckConstraint(condition=models.Q(('year__gte', 1950)), name='constructor_standings_year_gte_1950')],
            },
        ),
        migrations.CreateModel(
            name='DriverLapAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('round_number', models.PositiveSmallIntegerField()),
                ('session', models.CharField(max_length=120)),
                ('driver_code', models.CharField(blank=True, max_length=3, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'driver_lap_analysis',
                'indexes': [models.Index(fields=['year', 'round_number', 'session'], name='idx_dla_session'), models.Index(fields=['year', 'driver_code'], name='idx_driver_lap_analysis_driver')],
                'constraints': [models.UniqueConstraint(fields=('year', 'round_number', 'session', 'driver_code'), name='uniq_driver_lap_analysis_year_round_session_driver'), models.CheckConstraint(condition=models.Q(('year__gte', 1950)), name='driver_lap_analysis_year_gte_1950'), models.CheckConstraint(condition=models.Q(('round_number__gte', 1)), name='driver_lap_analysis_round_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='DriverStandings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('driver_code', models.CharField(blank=True, max_length=3, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'driver_standings',
                'indexes': [models.Index(fields=['year'], name='idx_driver_standings_year'), models.Index(fields=['driver_code'], name='idx_driver_standings_driver')],
                'constraints': [models.UniqueConstraint(fields=('year', 'driver_code'), name='uniq_driver_standings_year_driver'), models.CheckConstraint(condition=models.Q(('year__gte', 1950), ('year__isnull', True), _connector='OR'), name='driver_standings_year_gte_1950_or_null')],
            },
        ),
        migrations.CreateModel(
            name='DriverTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('round_number', models.PositiveSmallIntegerField()),
                ('session', models.CharField(max_length=120)),
                ('driver_code', models.CharField(blank=True, max_length=3, null=True)),
                ('lap', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'driver_telemetry',
                'indexes': [models.Index(fields=['year', 'round_number', 'session'], name='idx_driver_telemetry_session'), models.Index(fields=['year', 'driver_code'], name='idx_driver_telemetry_driver')],
                'constraints': [models.UniqueConstraint(fields=('year', 'round_number', 'session', 'driver_code', 'lap'), name='uniq_driver_telemetry_year_round_session_driver_lap'), models.CheckConstraint(condition=models.Q(('year__gte', 1950)), name='driver_telemetry_year_gte_1950'), models.CheckConstraint(condition=models.Q(('round_number__gte', 1)), name='driver_telemetry_round_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='PracticeResultData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('round_number', models.PositiveSmallIntegerField()),
                ('session', models.CharField(max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'practice_results',
                'indexes': [models.Index(fields=['year', 'round_number'], name='idx_prd_year_round')],
                'constraints': [models.UniqueConstraint(fields=('year', 'round_number', 'session'), name='uniq_practice_result_data_year_round_session'), models.CheckConstraint(condition=models.Q(('year__gte', 1950)), name='practice_result_data_year_gte_1950'), models.CheckConstraint(condition=models.Q(('round_number__gte', 1)), name='practice_result_data_round_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='QualifyingResultData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('round_number', models.PositiveSmallIntegerField()),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'qualifying_results',
                'indexes': [models.Index(fields=['year', 'round_number'], name='idx_qrd_year_round')],
                'constraints': [models.UniqueConstraint(fields=('year', 'round_number'), name='uniq_qualifying_result_data_year_round'), models.CheckConstraint(condition=models.Q(('year__gte', 1950)), name='qualifying_result_data_year_gte_1950'), models.CheckConstraint(condition=models.Q(('round_number__gte', 1)), name='qualifying_result_data_round_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='RaceResultData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('round_number', models.PositiveSmallIntegerField()),
                ('session', models.CharField(max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'race_results',
                'indexes': [models.Index(fields=['year', 'round_number'], name='idx_rrd_year_round')],
                'constraints': [models.UniqueConstraint(fields=('year', 'round_number', 'session'), name='uniq_race_result_data_year_round_session'), models.CheckConstraint(condition=models.Q(('year__gte', 1950)), name='race_result_data_year_gte_1950'), models.CheckConstraint(condition=models.Q(('round_number__gte', 1)), name='race_result_data_round_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='SeasonSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'season_schedule',
                'indexes': [models.Index(fields=['year'], name='idx_season_schedule_year')],
                'constraints': [models.CheckConstraint(condition=models.Q(('year__gte', 1950)), name='season_schedule_year_gte_1950')],
            },
        ),
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('round_number', models.PositiveSmallIntegerField()),
                ('session', models.CharField(max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'session_data',
                'indexes': [models.Index(fields=['year', 'round_number'], name='idx_session_data_year_round'), models.Index(fields=['year', 'session'], name='idx_session_data_year_session')],
                'constraints': [models.UniqueConstraint(fields=('year', 'round_number', 'session'), name='uniq_session_data_year_round_session'), models.CheckConstraint(condition=models.Q(('year__gte', 1950)), name='session_data_year_gte_1950'), models.CheckConstraint(condition=models.Q(('round_number__gte', 1)), name='session_data_round_gte_1')],
            },
        ),
    ]
