# Generated by Django 6.0.4 on 2026-05-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_drivermetric_idx_metric_race_consistency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_key', models.CharField(db_index=True, help_text="Unique task identifier (e.g., 'standings:2025', 'telemetry:2025:8:2:VER:1')", max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Task queued, waiting for worker'), ('running', 'Task started on worker'), ('complete', 'Task completed successfully, DB row written'), ('failed', 'Task failed, error_message populated')], db_index=True, default='pending', help_text='Task lifecycle state: pending → running → complete or failed', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, help_text='UUID of the Celery task (set after dispatch)', max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Exception traceback if status=failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the task was enqueued')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the task completed or failed', null=True)),
            ],
            options={
                'db_table': 'celery_task_record',
                'indexes': [models.Index(fields=['status'], name='idx_task_record_status'), models.Index(fields=['task_key', 'status'], name='idx_task_record_key_status')],
            },
        ),
    ]
