# Generated by Django 6.0.4 on 2026-05-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_drop_background_task_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecord',
            name='task_key',
            field=models.CharField(db_index=True, help_text="Unique task identifier (e.g., 'standings:2025', 'session:2025:8:R')", max_length=255, unique=True),
        ),
    ]
