# Generated by Django 6.0.4 on 2026-05-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_taskrecord_task_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_code', models.CharField(max_length=3, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'driver_career',
                'indexes': [models.Index(fields=['driver_code'], name='idx_driver_career_code')],
            },
        ),
        migrations.CreateModel(
            name='DriverSeasonBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_code', models.CharField(max_length=3)),
                ('year', models.PositiveSmallIntegerField()),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'driver_season_breakdown',
                'indexes': [models.Index(fields=['driver_code'], name='idx_drv_season_brkdown_code'), models.Index(fields=['year'], name='idx_drv_season_brkdown_year')],
                'constraints': [models.UniqueConstraint(fields=('driver_code', 'year'), name='uniq_driver_season_breakdown_code_year'), models.CheckConstraint(condition=models.Q(('year__gte', 1950)), name='driver_season_breakdown_year_gte_1950')],
            },
        ),
    ]
