# Generated by Django 6.0.4 on 2026-05-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_driver_career_season_breakdown'),
    ]

    operations = [
        # Truncate existing per-lap rows — the new constraint is per-driver,
        # so per-lap rows from the old schema would violate it.
        # driver_telemetry is a pure cache; data will be re-populated on demand.
        migrations.RunSQL(
            "TRUNCATE TABLE driver_telemetry;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveConstraint(
            model_name='drivertelemetry',
            name='uniq_driver_telemetry_year_round_session_driver_lap',
        ),
        migrations.RemoveIndex(
            model_name='drivertelemetry',
            name='idx_driver_telemetry_session',
        ),
        migrations.RemoveIndex(
            model_name='drivertelemetry',
            name='idx_driver_telemetry_driver',
        ),
        migrations.AddConstraint(
            model_name='drivertelemetry',
            constraint=models.UniqueConstraint(fields=('year', 'round_number', 'session', 'driver_code'), name='uniq_driver_telemetry_year_round_session_driver'),
        ),
    ]
