# Generated by Django 6.0.4 on 2026-05-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_telemetry_per_driver_session'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='constructorstandings',
            name='idx_constructor_standings_year',
        ),
        migrations.RemoveIndex(
            model_name='drivercareer',
            name='idx_driver_career_code',
        ),
        migrations.RemoveIndex(
            model_name='driverlapanalysis',
            name='idx_dla_session',
        ),
        migrations.RemoveIndex(
            model_name='driverlapanalysis',
            name='idx_driver_lap_analysis_driver',
        ),
        migrations.RemoveIndex(
            model_name='sessiondata',
            name='idx_session_data_year_round',
        ),
        migrations.RemoveIndex(
            model_name='sessiondata',
            name='idx_session_data_year_session',
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Task queued, waiting for worker'), ('running', 'Task started on worker'), ('complete', 'Task completed successfully, DB row written'), ('failed', 'Task failed, error_message populated')], default='pending', help_text='Task lifecycle state: pending → running → complete or failed', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='task_key',
            field=models.CharField(help_text="Unique task identifier (e.g., 'standings:2025', 'session:2025:8:R')", max_length=255, unique=True),
        ),
    ]
