# Generated by Django 6.0.4 on 2026-05-18 12:00
# Phase 1: Problem #9 — Add missing DB indexes for optimal query performance

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_constructorstandings_idx_constructor_standings_year_and_more'),
    ]

    operations = [
        # DriverLapAnalysis — add indexes for (year, round_number) and (year, round_number, driver_code) queries
        migrations.AddIndex(
            model_name='driverlapanalysis',
            index=models.Index(fields=['year', 'round_number'], name='idx_dla_year_round'),
        ),
        migrations.AddIndex(
            model_name='driverlapanalysis',
            index=models.Index(fields=['year', 'round_number', 'driver_code'], name='idx_dla_year_round_driver'),
        ),
        
        # DriverTelemetry — add index for (year, round_number) queries
        migrations.AddIndex(
            model_name='drivertelemetry',
            index=models.Index(fields=['year', 'round_number'], name='idx_dt_year_round'),
        ),
        
        # SessionData — add index for (year, round_number) queries
        migrations.AddIndex(
            model_name='sessiondata',
            index=models.Index(fields=['year', 'round_number'], name='idx_sd_year_round'),
        ),
        
        # ConstructorStandings — add index for year queries
        migrations.AddIndex(
            model_name='constructorstandings',
            index=models.Index(fields=['year'], name='idx_constructor_standings_year'),
        ),
    ]
