# Generated by Django 6.0.4 on 2026-05-22 20:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_missing_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('key', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], db_index=True, default='free', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('request_count', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'api_apikey',
                'indexes': [models.Index(fields=['email', 'is_active'], name='api_apikey_email_ab8729_idx'), models.Index(fields=['tier', 'is_active'], name='api_apikey_tier_b911dc_idx')],
            },
        ),
    ]
