# Generated by Django 6.0.4 on 2026-05-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_apikey_tier_rename'),
    ]

    operations = [
        migrations.CreateModel(
            name='F1Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(db_index=True, help_text="Unique Jolpica identifier (e.g., 'max_verstappen')", max_length=100, unique=True)),
                ('code', models.CharField(blank=True, db_index=True, help_text="3-letter driver code (e.g., 'VER', 'HAM')", max_length=10, null=True)),
                ('number', models.CharField(blank=True, help_text="Car permanent number (e.g., '1')", max_length=10, null=True)),
                ('given_name', models.CharField(help_text='First name', max_length=100)),
                ('family_name', models.CharField(db_index=True, help_text='Last name (indexed for search)', max_length=100)),
                ('nationality', models.CharField(blank=True, help_text='Country of origin', max_length=100, null=True)),
                ('dob', models.CharField(blank=True, help_text='Date of birth (YYYY-MM-DD)', max_length=20, null=True)),
                ('seasons', models.JSONField(default=list, help_text='List of years driver competed [2015, 2016, ...]')),
            ],
            options={
                'verbose_name': 'F1 Driver',
                'verbose_name_plural': 'F1 Drivers',
                'ordering': ['family_name', 'given_name'],
                'indexes': [models.Index(fields=['family_name', 'given_name'], name='api_f1drive_family__e2a45d_idx'), models.Index(fields=['code'], name='api_f1drive_code_00e48a_idx')],
            },
        ),
    ]
