# Generated by Django 6.0.4 on 2026-05-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_f1driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='F1Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, unique=True)),
                ('driver_id', models.CharField(max_length=100)),
                ('driver_code', models.CharField(blank=True, max_length=10, null=True)),
                ('driver_name', models.CharField(max_length=200)),
                ('team', models.CharField(blank=True, max_length=200, null=True)),
                ('points', models.FloatField(blank=True, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'F1 Champion',
                'verbose_name_plural': 'F1 Champions',
                'ordering': ['-year'],
            },
        ),
    ]
