# Generated by Django 6.0.4 on 2026-06-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_f1champion'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrecord',
            name='meta',
            field=models.JSONField(blank=True, help_text='Optional metadata emitted by the worker (timings, counts)', null=True),
        ),
    ]
