# Generated by Django 6.0.4 on 2026-06-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_taskrecord_drop_celery_task_id_add_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskrecord',
            name='meta',
        ),
        migrations.CreateModel(
            name='DRSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('round_number', models.PositiveSmallIntegerField()),
                ('session', models.CharField(max_length=120)),
                ('driver_code', models.CharField(max_length=10)),
                ('lap', models.PositiveSmallIntegerField()),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('location_gained_on', models.CharField(blank=True, max_length=100, null=True)),
                ('gap_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drs_data',
                'indexes': [models.Index(fields=['year', 'round_number', 'session'], name='idx_drs_year_round_session'), models.Index(fields=['year', 'round_number'], name='idx_drs_year_round')],
                'constraints': [models.CheckConstraint(condition=models.Q(('year__gte', 1950)), name='drs_data_year_gte_1950'), models.CheckConstraint(condition=models.Q(('round_number__gte', 1)), name='drs_data_round_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='IncidentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('round_number', models.PositiveSmallIntegerField()),
                ('session', models.CharField(max_length=120)),
                ('driver_code_a', models.CharField(max_length=10)),
                ('driver_code_b', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('lap', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'incident_data',
                'indexes': [models.Index(fields=['year', 'round_number', 'session'], name='idx_id_year_round_session'), models.Index(fields=['year', 'round_number'], name='idx_id_year_round')],
                'constraints': [models.CheckConstraint(condition=models.Q(('year__gte', 1950)), name='incident_data_year_gte_1950'), models.CheckConstraint(condition=models.Q(('round_number__gte', 1)), name='incident_data_round_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='PitStopData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('round_number', models.PositiveSmallIntegerField()),
                ('session', models.CharField(max_length=120)),
                ('driver_code', models.CharField(max_length=10)),
                ('lap', models.PositiveSmallIntegerField()),
                ('duration', models.FloatField(blank=True, null=True)),
                ('compound_in', models.CharField(blank=True, max_length=20, null=True)),
                ('compound_out', models.CharField(blank=True, max_length=20, null=True)),
                ('new_tyres', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pit_stop_data',
                'indexes': [models.Index(fields=['year', 'round_number', 'session'], name='idx_ps_year_round_session'), models.Index(fields=['year', 'round_number'], name='idx_ps_year_round')],
                'constraints': [models.CheckConstraint(condition=models.Q(('year__gte', 1950)), name='pit_stop_data_year_gte_1950'), models.CheckConstraint(condition=models.Q(('round_number__gte', 1)), name='pit_stop_data_round_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='PositionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('round_number', models.PositiveSmallIntegerField()),
                ('session', models.CharField(max_length=120)),
                ('driver_code', models.CharField(max_length=10)),
                ('lap', models.PositiveSmallIntegerField()),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('position_change', models.SmallIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'position_data',
                'indexes': [models.Index(fields=['year', 'round_number', 'session'], name='idx_pd_year_round_session'), models.Index(fields=['year', 'round_number'], name='idx_pd_year_round')],
                'constraints': [models.CheckConstraint(condition=models.Q(('year__gte', 1950)), name='position_data_year_gte_1950'), models.CheckConstraint(condition=models.Q(('round_number__gte', 1)), name='position_data_round_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='TrackStatusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('round_number', models.PositiveSmallIntegerField()),
                ('session', models.CharField(max_length=120)),
                ('lap', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(max_length=50)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'track_status_data',
                'indexes': [models.Index(fields=['year', 'round_number', 'session'], name='idx_ts_year_round_session'), models.Index(fields=['year', 'round_number'], name='idx_ts_year_round')],
                'constraints': [models.CheckConstraint(condition=models.Q(('year__gte', 1950)), name='track_status_data_year_gte_1950'), models.CheckConstraint(condition=models.Q(('round_number__gte', 1)), name='track_status_data_round_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('round_number', models.PositiveSmallIntegerField()),
                ('session', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField()),
                ('air_temp', models.FloatField(blank=True, null=True)),
                ('track_temp', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wind_direction', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'weather_data',
                'indexes': [models.Index(fields=['year', 'round_number', 'session'], name='idx_wd_year_round_session'), models.Index(fields=['year', 'round_number'], name='idx_wd_year_round')],
                'constraints': [models.CheckConstraint(condition=models.Q(('year__gte', 1950)), name='weather_data_year_gte_1950'), models.CheckConstraint(condition=models.Q(('round_number__gte', 1)), name='weather_data_round_gte_1')],
            },
        ),
    ]
