"""
Django settings for f1_project project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

import dotenv
import dj_database_url
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from backend/.env
dotenv.load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Set via environment variable; defaults to False in production
DEBUG = config('DEBUG', default=False, cast=bool)

# Required for production; set via environment variable
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = True


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'api.apps.ApiConfig',
    'anymail',
]

MIDDLEWARE = [
    'api.common.request_id.RequestIdMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'api.middleware.csrf_exempt.CsrfExemptSessionMiddleware',  # Must run before CsrfViewMiddleware
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'f1_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'api.permissions.IsAPIKeyAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.auth.APIKeyAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'api.throttling.APIKeyThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'api_key_throttle': '100/min',  # Free tier default; actual rate determined by tier
    },
    'EXCEPTION_HANDLER': 'api.exception_handlers.custom_exception_handler',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'F1 Stats Dashboard API',
    'DESCRIPTION': (
        'F1 analytics API. Register at /api/auth/register/ to get an API key. '
        'Click Authorize and enter your key to test endpoints.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SECURITY': [{'ApiKeyAuth': []}],
    'COMPONENTS': {
        'securitySchemes': {
            'ApiKeyAuth': {
                'type': 'apiKey',
                'in': 'header',
                'name': 'X-API-Key',
                'description': 'Your API key UUID. Register at /api/auth/register/ to get one.',
            }
        }
    },
}

WSGI_APPLICATION = 'f1_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.parse(
        url=os.getenv("DATABASE_URL", ""),
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# Email configuration — SMTP (Gmail) backend
# ---------------------------------------------------------------------------
# Configure Django to send email via SMTP. Supply the credentials via
# environment variables: EMAIL_HOST_USER and EMAIL_HOST_PASSWORD.
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")

# Default from address for transactional emails; use the SMTP user by default
DEFAULT_FROM_EMAIL = config("EMAIL_HOST_USER", default="noreply@your-sender-name.com")
SITE_BASE_URL = config("SITE_BASE_URL", default="http://localhost:8000")

# Secret for admin operations (kept for SPECTACULAR_SETTINGS reference)
ADMIN_SECRET = config("ADMIN_SECRET", default="")
# Password for POST /api/auth/{INTERNAL_KEY_PATH}/ endpoint
INTERNAL_KEY_PASSWORD = config("INTERNAL_KEY_PASSWORD", default="")
# URL path suffix for internal key generation — set to a UUID in production
INTERNAL_KEY_PATH = config("INTERNAL_KEY_PATH", default="internal-key")

# Optional fast internal API key: when set, requests presenting this exact
# key are accepted immediately without a DB lookup or usage updates.
INTERNAL_API_KEY = config("INTERNAL_API_KEY", default="")

# ---------------------------------------------------------------------------
# Redis URLs — all read from environment, no hardcoded fallbacks in production
# ---------------------------------------------------------------------------
REDIS_1_URL = config("REDIS_1_URL", default="redis://127.0.0.1:6379/1")
REDIS_2_URL = config("REDIS_2_URL", default="redis://127.0.0.1:6379/2")
REDIS_3_URL = config("REDIS_3_URL", default="redis://127.0.0.1:6379/0")
REDIS_4_URL = config("REDIS_4_URL", default="redis://127.0.0.1:6379/3")

# ---------------------------------------------------------------------------
# Celery queue (Celery + Redis + django-celery-results)
# ---------------------------------------------------------------------------
CELERY_BROKER_URL = REDIS_3_URL
CELERY_RESULT_BACKEND = REDIS_3_URL.replace("/0", "/1")
CELERY_IGNORE_RESULT = False  # Changed in Phase 3 to track task results in result backend
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"

# ---------------------------------------------------------------------------
# Celery Queue Routing — Phase 3: Tiered queues with worker pools
# ---------------------------------------------------------------------------
CELERY_TASK_QUEUES = {
    "tier1_instant": {
        "exchange": "tier1_instant",
        "routing_key": "tier1_instant",
        "priority": 10,
    },
    "tier2_fast": {
        "exchange": "tier2_fast",
        "routing_key": "tier2_fast",
        "priority": 7,
    },
    "tier3_medium": {
        "exchange": "tier3_medium",
        "routing_key": "tier3_medium",
        "priority": 5,
    },
    "tier4_telemetry": {
        "exchange": "tier4_telemetry",
        "routing_key": "tier4_telemetry",
        "priority": 2,
    },
    
    "tier6_notifications": {
        "exchange": "tier6_notifications",
        "routing_key": "tier6_notifications",
        "priority": 4,
    }
}

CELERY_TASK_ROUTES = {
    # Tier 1: Instant (standings, schedule, career) — 30s dedup TTL
    "api.tasks.populate_standings": {"queue": "tier1_instant"},
    "api.tasks.populate_constructor_standings": {"queue": "tier1_instant"},
    "api.tasks.populate_driver_career": {"queue": "tier1_instant"},
    "api.tasks.populate_driver_season": {"queue": "tier1_instant"},
    "api.tasks.populate_schedule": {"queue": "tier1_instant"},
    
    # Tier 2: Fast (results, session data) — 60s dedup TTL
    "api.tasks.populate_race_results": {"queue": "tier2_fast"},
    
    # Tier 3: Medium (laps, analysis) — 90s dedup TTL
    "api.tasks.populate_laps": {"queue": "tier3_medium"},
    "api.tasks.populate_pace": {"queue": "tier3_medium"},
    "api.tasks.populate_stints": {"queue": "tier3_medium"},
    "api.tasks.populate_sectors": {"queue": "tier3_medium"},
    "api.tasks.populate_positions": {"queue": "tier3_medium"},
    "api.tasks.populate_drs": {"queue": "tier3_medium"},
    "api.tasks.populate_tyre_strategy": {"queue": "tier3_medium"},
    
    # Tier 4: Telemetry (ack_late=True) — 180s dedup TTL
    "api.tasks.populate_telemetry": {"queue": "tier4_telemetry"},
    "api.tasks.populate_telemetry_overlay": {"queue": "tier4_telemetry"},
    "api.tasks.populate_telemetry_summary": {"queue": "tier4_telemetry"},


    # Tier 6: Notifications
    "api.tasks.send_api_key_email": {"queue": "tier6_notifications"},
    "api.tasks.send_rate_limit_warning": {"queue": "tier6_notifications"},
    "api.tasks.send_usage_summary": {"queue": "tier6_notifications"},
    "api.tasks.send_usage_summary_all": {"queue": "tier6_notifications"},

}

# ---------------------------------------------------------------------------
# Cache — Phase 4: Three-tier Redis cache architecture with bounded LRU
# ---------------------------------------------------------------------------
# Redis 1: App cache — non-telemetry results, standings, incidents
# Redis 2: Telemetry cache — dedicated telemetry traces to prevent eviction of hot data
# Redis 3: Celery broker (handled by CELERY_BROKER_URL above)
# Redis 4: Rate limiting — separate namespace to avoid eviction conflicts
#
# REQUIRED REDIS SERVER CONFIGURATION (set via redis-cli or config file):
#   REDIS 1 (main app cache):
#     CONFIG SET maxmemory 1gb
#     CONFIG SET maxmemory-policy allkeys-lru
#   REDIS 2 (telemetry cache):
#     CONFIG SET maxmemory 200mb
#     CONFIG SET maxmemory-policy allkeys-lru
#   REDIS 3 (Celery broker):
#     CONFIG SET maxmemory-policy noeviction

CACHES = {
    "default": {
        # Redis 1: Main app cache (500MB–1GB ceiling, allkeys-lru eviction)
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_1_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_CLASS": "redis.connection.BlockingConnectionPool",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 50,
                "timeout": 10,
                "retry_on_timeout": True,
            },
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
        },
        "KEY_PREFIX": "cache",
        "TIMEOUT": 300,  # Default 5 min TTL; overridden per key via cache.set(key, val, timeout=...)
    },
    "telemetry_cache": {
        # Redis 2: Dedicated telemetry cache (200MB ceiling, allkeys-lru eviction)
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_2_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_CLASS": "redis.connection.BlockingConnectionPool",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 20,
                "timeout": 10,
                "retry_on_timeout": True,
            },
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
        },
        "KEY_PREFIX": "telemetry",
        "TIMEOUT": 300,  # Default 5 min TTL; overridden per key via cache.set(key, val, timeout=...)
    },
    "rate_limit": {
        # Redis 4: Rate limiting cache — separate namespace to prevent eviction conflicts
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_4_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_CLASS": "redis.connection.BlockingConnectionPool",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 20,
                "timeout": 10,
                "retry_on_timeout": True,
            },
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
        },
        "KEY_PREFIX": "rate_limit",
        "TIMEOUT": None,
    },
}

# ---------------------------------------------------------------------------
# Logging — queue lifecycle observability
# Console + rotating file backend/logs/queue.log (10 MB × 5 backups)
# Trace order: api_cache_miss → enqueue_created → task_started → command_store_success → task_finished
# ---------------------------------------------------------------------------
_LOG_DIR = BASE_DIR / "logs"
os.makedirs(_LOG_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "queue": {
            "format": "[%(asctime)s] %(levelname)s %(name)s | %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "verbose": {
            "format": "[%(asctime)s] %(levelname)s pid=%(process)d worker=%(processName)s %(name)s | %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "queue_file": {
            "class": "logging.FileHandler",
            "filename": str(_LOG_DIR / "queue.log"),
            "formatter": "verbose",
            "encoding": "utf-8",
        },
    },
    "loggers": {
        "api.services.tasks": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "api.services.drivers": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "api.services.results": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "api.services.analysis": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "api.views": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "api.management.commands.populate_standings": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "api.management.commands.populate_race": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "api.management.commands.populate_session": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "api.management.commands.populate_telemetry": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "background_task": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "api.services.task_manager": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console", "queue_file"], "level": "DEBUG", "propagate": False,
        },
        "fastf1": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "api.session": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "api.services": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "api.schedule": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "api.results": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "api.drivers": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "api.constructors": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "api.queue": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
    },
}