"""
Django settings for f1_project project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

import dotenv
import dj_database_url
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from backend/.env
dotenv.load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$k4f=^#+m)2ytwd7ntqm74lfs=d5bgst1#$!huj&8k!d1ckw^0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'f1_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'F1 Stats Dashboard API',
    'DESCRIPTION': 'OpenAPI schema for F1 analytics, unified FastF1 data, and persistence coverage endpoints.',
    'VERSION': '1.0.0',
}

WSGI_APPLICATION = 'f1_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.parse(
        url=os.getenv("DATABASE_URL", ""),
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'



SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', cast=bool)

# ---------------------------------------------------------------------------
# Celery queue (Celery + Redis + django-celery-results)
# ---------------------------------------------------------------------------
CELERY_BROKER_URL = os.getenv(
    "REDIS_URL",
    "redis://localhost:6379/0"  # Local dev default
)
CELERY_IGNORE_RESULT = True
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"

# ---------------------------------------------------------------------------
# Logging — queue lifecycle observability
# Console + rotating file backend/logs/queue.log (10 MB × 5 backups)
# Trace order: api_cache_miss → enqueue_created → task_started → command_store_success → task_finished
# ---------------------------------------------------------------------------
_LOG_DIR = BASE_DIR / "logs"
os.makedirs(_LOG_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "queue": {
            "format": "[%(asctime)s] %(levelname)s %(name)s | %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "queue",
        },
        "queue_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(_LOG_DIR / "queue.log"),
            "maxBytes": 10 * 1024 * 1024,  # 10 MB per file
            "backupCount": 5,
            "formatter": "queue",
            "encoding": "utf-8",
        },
    },
    "loggers": {
        "api.services.tasks": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "api.services.drivers": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "api.services.results": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "api.services.analysis": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "api.views": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "api.management.commands.populate_standings": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "api.management.commands.populate_race": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "api.management.commands.populate_session": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "api.management.commands.populate_telemetry": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "background_task": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
        "api.services.task_manager": {
            "handlers": ["console", "queue_file"], "level": "INFO", "propagate": False,
        },
    },
}